# Crashes Near Point

Find the crash incident_id for a specific crash given its location and time.

In [1]:
import folium
import datetime
import pandas as pd
from folium.plugins import HeatMap

import os
os.chdir('..')
from scripts.crash_data_analysis import CrashDataAnalysis

In [2]:
cda = CrashDataAnalysis()
# df = cda.crash_dataframe(verbose=True)

In [3]:
num_years = 5

# when the point doesn't automatically geocode
# geocoded_location = 'E 1st Ave and N Gilpin St, Denver, CO'
# lat_lon = [39.71824953362511, -104.96668328236497] # 'E 1st Ave and N Gilpin St, Denver, CO'

# geocoded_location = 'S Zuni St and W Arkansas Ave, Denver, CO'
# geocoded_location = 'Godsman Elementary School, Denver, CO'
# geocoded_location = 'W 26th Ave and Tennyson St, Denver, CO'
# geocoded_location = 'E 1st Ave and N Gilpin St, Denver, CO'
# geocoded_location = 'E 32nd Ave and Sheridan Blvd, Denver, CO'
# geocoded_location = '700 E. Colfax Avenue, Denver, CO'
# geocoded_location = 'Montview & Cherry, Denver, CO'
# geocoded_location = 'W 14th Ave & Federal Blvd, Denver, CO'
# geocoded_location = 'E 17th Ave & Holly, Denver, CO'
geocoded_location = 'E 17th Ave & Hudson, Denver, CO' # hit and run at Saturday 8/2/2025 4pm

# crash occurred within this distance of the given latitude and longitude
radius_miles = 0.125

lat_lon = cda.geocode_location(geocoded_location)
lat_lon

[39.7433984, -104.9234614]

In [4]:
query = f"""
select
*
, reported_date at time zone 'America/Denver' as reported_date_local
, ST_Distance(
    geom_denver, ST_Transform(ST_SetSRID(ST_MakePoint({lat_lon[1]},{lat_lon[0]}), 4326), 3502)
) as distance_feet

from crashes

where geo_lon is not null
and ST_Distance(
    geom_denver, ST_Transform(ST_SetSRID(ST_MakePoint({lat_lon[1]},{lat_lon[0]}), 4326), 3502)
    ) < {radius_miles * 5280}

order by reported_date
"""
# and extract(year from reported_date) >= 2022

nearby = pd.read_sql(query, cda.conn)

nearby['reported_date_local'] = nearby['reported_date_local'].dt.tz_localize('America/Denver')

In [5]:
nearby.groupby(nearby.reported_date.dt.year).agg(
    crashes=('incident_id', 'count')
    , fatalities=('fatality', 'sum')
    , sbi=('sbi', 'sum')
    , pedestrian_ind=('pedestrian_ind', 'sum')
    , bicycle_ind=('bicycle_ind', 'sum')
).astype(int) #.to_clipboard()

               crashes  fatalities  sbi  pedestrian_ind  bicycle_ind
reported_date
2014                 4           1    0               0            0
2015                 5           0    0               0            0
2016                 4           0    0               0            0
2017                 5           0    0               0            0
2018                 5           0    0               0            1
2019                 5           0    0               0            0
2020                 3           0    0               0            0
2021                 1           0    0               0            1
2022                 2           0    0               0            0
2023                 2           0    0               0            0
2025                 3           0    0               0            0

In [6]:
nearby['all_time'] = 'all time'
nearby.groupby('all_time').agg(
    crashes=('incident_id', 'count')
    , fatalities=('fatality', 'sum')
    , sbi=('sbi', 'sum')
    , pedestrian_ind=('pedestrian_ind', 'sum')
    , bicycle_ind=('bicycle_ind', 'sum')
).astype(int)

          crashes  fatalities  sbi  pedestrian_ind  bicycle_ind
all_time
all time       39           1    0               0            2

In [7]:
display_df = nearby.copy()
display_df['bicycle'] = display_df['bicycle_ind'].replace(0, '').replace(1, True)
display_df['pedestrian'] = display_df['pedestrian_ind'].replace(0, '').replace(1, True)
display_df['serious_injury'] = display_df['sbi'].replace(False, '')
display_df['fatal'] = display_df['fatality'].replace(False, '')

display_cols = [
    'reported_date_local'
    , 'top_traffic_accident_offense'
    , 'incident_address_corrected'
    , 'bicycle'
    , 'pedestrian'
    , 'serious_injury'
    , 'fatal'
    , 'distance_feet'
    , 'incident_id'
]

# nearby.to_clipboard()
# nearby[display_cols]
# display_df.loc[display_df.pedestrian_ind == 1, display_cols]
display_df[display_cols].tail(10)

,reported_date_local,top_traffic_accident_offense,incident_address_corrected,bicycle,pedestrian,serious_injury,fatal,distance_feet,incident_id
29,2020-02-14 13:34:00-07:00,TRAF - ACCIDENT - HIT & RUN,5401 E 17TH AVE,,,,,346.305912,202097971
30,2020-10-08 08:01:00-06:00,TRAF - ACCIDENT,E 17TH AVE / N HUDSON ST,,,,,122.876187,2020601131
31,2021-03-24 16:17:00-06:00,TRAF - ACCIDENT,E 17TH AVE / N HUDSON ST,True,,,,122.876187,2021168279
32,2022-03-06 21:21:00-07:00,TRAF - ACCIDENT - HIT & RUN,N GRAPE ST / E 17TH AVE,,,,,350.594282,2022113308
33,2022-06-05 04:41:00-06:00,TRAF - ACCIDENT - HIT & RUN,E 16TH AVE / N GRAPE ST,,,,,632.177695,2022282952
34,2023-09-26 17:03:00-06:00,TRAF - ACCIDENT,E 17TH AVE / N HUDSON ST,,,,,2.776202,2023519913
35,2023-12-28 12:54:00-07:00,TRAF - ACCIDENT - HIT & RUN,E 17TH AVE / N HUDSON ST,,,,,2.776202,2023691092
36,2025-01-24 15:19:00-07:00,TRAF - ACCIDENT,E 17TH AVE / N HOLLY ST,,,,,333.526974,202541175
37,2025-03-13 07:58:00-06:00,TRAF - ACCIDENT,E 17TH AVE / N HUDSON ST,,,,,2.776202,2025127294
38,2025-08-02 18:44:00-06:00,TRAF - ACCIDENT - HIT & RUN,E 17TH AVE / N HUDSON ST,,,,,122.876187,2025409018

In [8]:
this_map = folium.Map(prefer_canvas=True)
HeatMap(nearby[['geo_lat', 'geo_lon']]).add_to(this_map)
folium.Circle(location=lat_lon, weight=2, radius=radius_miles*1609.34).add_to(this_map)
this_map.fit_bounds(
    [nearby[['geo_lat', 'geo_lon']].min().values.tolist()
     , nearby[['geo_lat', 'geo_lon']].max().values.tolist()]
)
this_map

In [9]:
# Text string with frequency of crashes

most_recent_timestamp = cda.most_recent_crash_timestamp()
start_timestamp = most_recent_timestamp - pd.DateOffset(years=num_years)
days_in_time_range = (most_recent_timestamp - start_timestamp).days

nearby_in_time_range = nearby[nearby.reported_date_local > start_timestamp].copy()

days_between_crashes = days_in_time_range / len(nearby_in_time_range)

print(
    f'The location "{geocoded_location}" has had {len(nearby_in_time_range)} traffic crashes'
    , f'within a {radius_miles} mile radius'
    , f'over the last {num_years} years, an average of {days_between_crashes:.1f} days between crashes.'
    , f'In that time, there were {nearby_in_time_range.fatality.sum()} deadly crashes'
    , f'and {nearby_in_time_range.sbi.sum()} crashes causing a serious bodily injury.'
    , f'There were {(nearby_in_time_range.pedestrian_ind > 0).sum()} crashes involving a pedestrian'
    , f'and {(nearby_in_time_range.bicycle_ind > 0).sum()} crashes involving a bicyclist.'
)

The location "E 17th Ave & Hudson, Denver, CO" has had 9 traffic crashes within a 0.125 mile radius over the last 5 years, an average of 202.9 days between crashes. In that time, there were 0 deadly crashes and 0 crashes causing a serious bodily injury. There were 0 crashes involving a pedestrian and 1 crashes involving a bicyclist.

In [10]:
cda.conn.dispose()

## Bike and ped crashes in nearby dataframe

In [11]:
nearby_in_time_range[nearby_in_time_range.bicycle_ind > 0]

,incident_id,top_traffic_accident_offense,reported_date,incident_address_corrected,at_freeway,geo_lon,geo_lat,neighborhood_id,bicycle_ind,pedestrian_ind,...,crash_date,crash_date_str,crash_time_str,crash_year,crash_day_of_year,geom,geom_denver,reported_date_local,distance_feet,all_time
31,2021168279,TRAF - ACCIDENT,2021-03-24 22:17:00+00:00,E 17TH AVE / N HUDSON ST,False,-104.92345,39.743736,South Park Hill,1.0,0.0,...,2021-03-24,2021-03-24 Wed,"Wed Mar 24, 4:17 PM",2021,83,0101000020E610000064D384CC193B5AC07B6F67BA32DF...,0101000020AE0D000040470C8008204841AB8D57002CE2...,2021-03-24 16:17:00-06:00,122.876187,all time

In [12]:
nearby_in_time_range[nearby_in_time_range.pedestrian_ind > 0]

Empty DataFrame
Columns: [incident_id, top_traffic_accident_offense, reported_date, incident_address_corrected, at_freeway, geo_lon, geo_lat, neighborhood_id, bicycle_ind, pedestrian_ind, day_or_night, driver_action, updated_at, sbi, fatality, sbi_or_fatality, crash_date, crash_date_str, crash_time_str, crash_year, crash_day_of_year, geom, geom_denver, reported_date_local, distance_feet, all_time]
Index: []

[0 rows x 26 columns]

In [13]:
nearby[(nearby.fatality)]

,incident_id,top_traffic_accident_offense,reported_date,incident_address_corrected,at_freeway,geo_lon,geo_lat,neighborhood_id,bicycle_ind,pedestrian_ind,...,crash_date,crash_date_str,crash_time_str,crash_year,crash_day_of_year,geom,geom_denver,reported_date_local,distance_feet,all_time
2,2014608335,TRAF - ACCIDENT - FATAL,2014-11-15 09:55:00+00:00,E 17TH AVE / N HOLLY ST,False,-104.922275,39.743395,South Park Hill,0.0,0.0,...,2014-11-15,2014-11-15 Sat,"Sat Nov 15, 2:55 AM",2014,319,0101000020E6100000D3463B8F063B5AC03F3B7D9027DF...,0101000020AE0D00000BCDDAFFAD20484189ADA9FFB1E1...,2014-11-15 02:55:00-07:00,333.526974,all time