# Most Dangerous Streets - Crash Leaderboard

Compare the most recent month to the all-time numbers to see which streets got safer.

In [1]:
import pytz
import folium
import pandas as pd
from datetime import datetime, timedelta

import os
os.chdir('..')
from scripts.crash_data_analysis import CrashDataAnalysis

In [2]:
cda = CrashDataAnalysis()

In [3]:
start_date = pytz.timezone('America/Denver').localize(datetime(2020,7,1))
end_date = cda.most_recent_crash_timestamp()

all_time = cda.street_metrics(start_date, end_date)

In [4]:
start_date = pytz.timezone('America/Denver').localize(datetime(2025,6,1))
end_date = pytz.timezone('America/Denver').localize(datetime(2025,7,1))

last_month = cda.street_metrics(start_date, end_date)

In [5]:
# A street must have at least 100 crashes all-time to be in the comparison
all_time = all_time[all_time.num_crashes >= 100].copy()

In [6]:
all_time

,gid,lrsroute,fullname,street_name_no_cardinal,length_miles,street_line,num_crashes,num_sbi,num_fatality,num_sbi_or_fatality,sum_bicycle_ind,sum_pedestrian_ind,days_in_data,days_between_crashes,crashes_per_mile_per_week,pedestrian_ind_per_mile_per_year
1793,3900,SPEERN BD,N SPEER BLVD,SPEER BLVD,2.634723,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",1149,35,8,43,18.0,37.0,1848,1.608355,1.651890,2.775588
831,1452,ESPEERN BD,E SPEER BLVD,SPEER BLVD,1.060124,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",357,9,2,11,5.0,6.0,1848,5.176471,1.275580,1.118621
2696,5587,PARK AV,PARK AVE W,PARK AVE W,1.809664,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",605,23,2,25,12.0,24.0,1848,3.054545,1.266349,2.621208
1990,4229,22ND ST,22ND ST,22ND ST,1.079568,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",353,10,2,12,6.0,19.0,1848,5.235127,1.238571,3.478500
1986,4225,20TH ST,20TH ST,20TH ST,1.453330,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",467,12,1,13,8.0,31.0,1848,3.957173,1.217163,4.215856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167,6778,SZUNI ST2,S ZUNI ST,ZUNI ST,2.981573,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",111,4,1,5,0.0,4.0,1848,16.648649,0.141018,0.265157
313,494,48TH AV6,E 48TH AVE,48TH AVE,2.758182,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",101,3,3,6,0.0,10.0,1848,18.297030,0.138706,0.716581
950,1661,HOLLY ST1,N HOLLY ST,HOLLY ST,3.763453,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",136,0,0,0,2.0,2.0,1848,13.588235,0.136883,0.105034
2819,6066,SMITH RD1,E SMITH RD,SMITH RD,2.852613,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",103,4,0,4,2.0,2.0,1848,17.941748,0.136770,0.138572
19,34,29TH AV1,E 29TH AVE,29TH AVE,3.723713,"{""type"":""MultiLineString"",""coordinates"":[[[-10...",110,2,1,3,1.0,5.0,1848,16.800000,0.111895,0.265388

In [7]:
comparison = pd.merge(
    all_time
    , last_month
    , how='inner'
    , on=['gid', 'lrsroute', 'fullname', 'length_miles','street_line']
    , suffixes=['_all_time', '_last_month']
)

In [8]:
comparison['diff_pmpw'] = (
    comparison['crashes_per_mile_per_week_last_month']
    - comparison['crashes_per_mile_per_week_all_time']
)

In [9]:
comparison['expected_crashes'] = (
    comparison['length_miles']
    * comparison['crashes_per_mile_per_week_all_time']
    * (comparison['days_in_data_last_month'] / 7)
)

comparison['diff_expected_crashes'] = comparison['num_crashes_last_month'] - comparison['expected_crashes']

## Difference in Crash Rate per Mile

In [10]:
this_map = folium.Map(prefer_canvas=True, tiles='CartoDB Positron')

good_streets = comparison.sort_values(by='diff_pmpw').head(5)['street_line']
bad_streets = comparison.sort_values(by='diff_pmpw').tail(5)['street_line']

for good_street in good_streets:
    folium.GeoJson(good_street, style_function=lambda x: {'color': 'green'}).add_to(this_map)

for bad_street in bad_streets:
    folium.GeoJson(bad_street, style_function=lambda x: {'color': 'red'}).add_to(this_map)
    
this_map.fit_bounds(this_map.get_bounds())
this_map

In [11]:
comparison.sort_values(by='diff_pmpw')[[
    'gid'
    , 'fullname'
    , 'length_miles'
    , 'crashes_per_mile_per_week_all_time'
    , 'crashes_per_mile_per_week_last_month'
    , 'diff_pmpw'
    , 'num_crashes_all_time'
    , 'num_crashes_last_month'
    , 'expected_crashes'
    , 'diff_expected_crashes'
]]

,gid,fullname,length_miles,crashes_per_mile_per_week_all_time,crashes_per_mile_per_week_last_month,diff_pmpw,num_crashes_all_time,num_crashes_last_month,expected_crashes,diff_expected_crashes
11,5372,PARK AVE,0.731422,1.103082,0.319013,-0.784068,213,1,3.457792,-2.457792
10,3811,WAZEE ST,0.624810,1.109428,0.373447,-0.735981,183,1,2.970779,-1.970779
34,4552,LEETSDALE DR,2.002250,0.802128,0.116536,-0.685592,424,1,6.883117,-5.883117
13,5579,N OSAGE ST,0.554444,1.038442,0.420842,-0.617600,152,1,2.467532,-1.467532
1,1452,E SPEER BLVD,1.060124,1.275580,0.660300,-0.615280,357,3,5.795455,-2.795455
...,...,...,...,...,...,...,...,...,...,...
65,4224,19TH ST,0.812553,0.540757,1.435804,0.895047,116,5,1.883117,3.116883
23,2941,N TOWER RD,1.027545,0.910526,2.043707,1.133181,247,9,4.009740,4.990260
39,4220,18TH ST,0.843447,0.718552,1.936498,1.217946,160,7,2.597403,4.402597
53,156,E 1ST AVE,1.225738,0.621147,1.903615,1.282468,201,10,3.262987,6.737013
31,3393,N UNIVERSITY BLVD,0.662389,0.817748,2.113563,1.295815,143,6,2.321429,3.678571

## Difference in Number of Expected Crashes

In [12]:
this_map = folium.Map(prefer_canvas=True, tiles='CartoDB Positron')

good_streets = comparison.sort_values(by='diff_expected_crashes').head(5)['street_line']
bad_streets = comparison.sort_values(by='diff_expected_crashes').tail(5)['street_line']

for good_street in good_streets:
    folium.GeoJson(good_street, style_function=lambda x: {'color': 'green'}).add_to(this_map)

for bad_street in bad_streets:
    folium.GeoJson(bad_street, style_function=lambda x: {'color': 'red'}).add_to(this_map)
    
this_map.fit_bounds(this_map.get_bounds())
this_map

In [13]:
comparison.sort_values(by='diff_expected_crashes')[[
    'gid'
    , 'fullname'
    , 'length_miles'
    , 'crashes_per_mile_per_week_all_time'
    , 'crashes_per_mile_per_week_last_month'
    , 'diff_pmpw'
    , 'expected_crashes'
    , 'num_crashes_last_month'
    , 'diff_expected_crashes'
]]

,gid,fullname,length_miles,crashes_per_mile_per_week_all_time,crashes_per_mile_per_week_last_month,diff_pmpw,expected_crashes,num_crashes_last_month,diff_expected_crashes
22,7584,S FEDERAL BLVD,4.373528,0.928451,0.586864,-0.341587,17.402597,11,-6.402597
34,4552,LEETSDALE DR,2.002250,0.802128,0.116536,-0.685592,6.883117,1,-5.883117
28,6476,S SANTA FE DR,3.537547,0.826630,0.461714,-0.364916,12.532468,7,-5.532468
5,1012,E COLFAX AVE,5.475202,1.202391,0.980177,-0.222214,28.214286,23,-5.214286
71,3890,N SHERIDAN BLVD,5.135898,0.525121,0.318023,-0.207098,11.558442,7,-4.558442
...,...,...,...,...,...,...,...,...,...
43,1799,N JOSEPHINE ST,1.876373,0.686366,1.243534,0.557168,5.519481,10,4.480519
23,2941,N TOWER RD,1.027545,0.910526,2.043707,1.133181,4.009740,9,4.990260
6,1714,N LINCOLN ST,2.165535,1.184185,1.831726,0.647541,10.990260,17,6.009740
53,156,E 1ST AVE,1.225738,0.621147,1.903615,1.282468,3.262987,10,6.737013
124,2938,N TOWER RD,7.211247,0.364015,0.582424,0.218409,11.250000,18,6.750000

In [14]:
comparison = comparison.sort_values(by='diff_expected_crashes')

comparison.loc[comparison['diff_expected_crashes'].rank() <= 5, 'Leaderboard'] = (
    comparison.loc[comparison['diff_expected_crashes'].rank() <= 5].apply(
        lambda row: f'{row.diff_expected_crashes:.0f} crashes'
        , axis=1
    )
)

comparison.loc[comparison['diff_expected_crashes'].rank(ascending=False) <= 5, 'Leaderboard'] = (
    comparison.loc[comparison['diff_expected_crashes'].rank(ascending=False) <= 5].apply(
        lambda row: f'+{row.diff_expected_crashes:.0f} crashes'
        , axis=1
    )
)

# comparison['Expected Crashes'] = comparison.expected_c

In [15]:
comparison['street_name'] = comparison['fullname'].str.title()
comparison.loc[
    comparison.Leaderboard.notnull()
    , ['street_name', 'expected_crashes', 'num_crashes_last_month', 'Leaderboard']
].style.format('{:.1f}', subset='expected_crashes')